### ISSUE TITLE
Timeout error with run.sh

### ISSUE THREAD

**Issue by marcusramberg** [Robertof/nixos-docker-sd-image-builder#13]
Getting a timeout error when trying this 
```
build-nixos_1   | /nix/store/diapjkxjqd07gl6pij2kyasfc96kmhaq-nixos-sd-image-20.03post-git-aarch64-linux.img
cleanup-qemu_1  | connect to [::ffff:172.18.0.2]:11111 from docker_build-nixos_1.docker_default:33061 ([::ffff:172.18.0.3]:33061)
cleanup-qemu_1  | build done
cleanup-qemu_1  | binfmt: detected x86 architecture, proceeding
cleanup-qemu_1  | binfmt: clearing existing entry for qemu-aarch64-docker-nixos
Exception in thread Thread-10:
Traceback (most recent call last):
  File "/nix/store/qd72pjvqlvfp6ghj3ndadflpqzmyh9as-python3.7-urllib3-1.25.9/lib/python3.7/site-packages/urllib3/connectionpool.py", line 426, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/nix/store/qd72pjvqlvfp6ghj3ndadflpqzmyh9as-python3.7-urllib3-1.25.9/lib/python3.7/site-packages/urllib3/connectionpool.py", line 421, in _make_request
    httplib_response = conn.getresponse()
  File "/nix/store/q732h09azy7lf0j30bnnhdl15p4rxpdy-python3-3.7.7/lib/python3.7/http/client.py", line 1344, in getresponse
    response.begin()
  File "/nix/store/q732h09azy7lf0j30bnnhdl15p4rxpdy-python3-3.7.7/lib/python3.7/http/client.py", line 306, in begin
    version, status, reason = self._read_status()
  File "/nix/store/q732h09azy7lf0j30bnnhdl15p4rxpdy-python3-3.7.7/lib/python3.7/http/client.py", line 267, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/nix/store/q732h09azy7lf0j30bnnhdl15p4rxpdy-python3-3.7.7/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nix/store/k9ivvbbycr1jr3b81jmnj2sq7ybs52sz-python3.7-requests-2.23.0/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/nix/store/qd72pjvqlvfp6ghj3ndadflpqzmyh9as-python3.7-urllib3-1.25.9/lib/python3.7/site-packages/urllib3/connectionpool.py", line 725, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/nix/store/qd72pjvqlvfp6ghj3ndadflpqzmyh9as-python3.7-urllib3-1.25.9/lib/python3.7/site-packages/urllib3/util/retry.py", line 403, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/nix/store/qd72pjvqlvfp6ghj3ndadflpqzmyh9as-python3.7-urllib3-1.25.9/lib/python3.7/site-packages/urllib3/packages/six.py", line 735, in reraise
    raise value
  File "/nix/store/qd72pjvqlvfp6ghj3ndadflpqzmyh9as-python3.7-urllib3-1.25.9/lib/python3.7/site-packages/urllib3/connectionpool.py", line 677, in urlopen
    chunked=chunked,
  File "/nix/store/qd72pjvqlvfp6ghj3ndadflpqzmyh9as-python3.7-urllib3-1.25.9/lib/python3.7/site-packages/urllib3/connectionpool.py", line 428, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/nix/store/qd72pjvqlvfp6ghj3ndadflpqzmyh9as-python3.7-urllib3-1.25.9/lib/python3.7/site-packages/urllib3/connectionpool.py", line 336, in _raise_timeout
    self, url, "Read timed out. (read timeout=%s)" % timeout_value
urllib3.exceptions.ReadTimeoutError: UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nix/store/q732h09azy7lf0j30bnnhdl15p4rxpdy-python3-3.7.7/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/nix/store/q732h09azy7lf0j30bnnhdl15p4rxpdy-python3-3.7.7/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/nix/store/p3g9654c0qhvgqv0alprypdqmbbpbidd-docker-compose-1.25.5/lib/python3.7/site-packages/compose/cli/log_printer.py", line 217, in watch_events
    for event in event_stream:
  File "/nix/store/p3g9654c0qhvgqv0alprypdqmbbpbidd-docker-compose-1.25.5/lib/python3.7/site-packages/compose/project.py", line 510, in yield_loop
    yield build_container_event(event)
  File "/nix/store/p3g9654c0qhvgqv0alprypdqmbbpbidd-docker-compose-1.25.5/lib/python3.7/site-packages/compose/project.py", line 478, in build_container_event
    container = Container.from_id(self.client, event['id'])
  File "/nix/store/p3g9654c0qhvgqv0alprypdqmbbpbidd-docker-compose-1.25.5/lib/python3.7/site-packages/compose/container.py", line 48, in from_id
    return cls(client, client.inspect_container(id), has_been_inspected=True)
  File "/nix/store/infb8g84lnxm83npfj98xf71p65czglp-python3.7-docker-4.2.0/lib/python3.7/site-packages/docker/utils/decorators.py", line 19, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/nix/store/infb8g84lnxm83npfj98xf71p65czglp-python3.7-docker-4.2.0/lib/python3.7/site-packages/docker/api/container.py", line 758, in inspect_container
    self._get(self._url("/containers/{0}/json", container)), True
  File "/nix/store/infb8g84lnxm83npfj98xf71p65czglp-python3.7-docker-4.2.0/lib/python3.7/site-packages/docker/utils/decorators.py", line 46, in inner
    return f(self, *args, **kwargs)
  File "/nix/store/infb8g84lnxm83npfj98xf71p65czglp-python3.7-docker-4.2.0/lib/python3.7/site-packages/docker/api/client.py", line 230, in _get
    return self.get(url, **self._set_request_timeout(kwargs))
  File "/nix/store/k9ivvbbycr1jr3b81jmnj2sq7ybs52sz-python3.7-requests-2.23.0/lib/python3.7/site-packages/requests/sessions.py", line 543, in get
    return self.request('GET', url, **kwargs)
  File "/nix/store/k9ivvbbycr1jr3b81jmnj2sq7ybs52sz-python3.7-requests-2.23.0/lib/python3.7/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/nix/store/k9ivvbbycr1jr3b81jmnj2sq7ybs52sz-python3.7-requests-2.23.0/lib/python3.7/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/nix/store/k9ivvbbycr1jr3b81jmnj2sq7ybs52sz-python3.7-requests-2.23.0/lib/python3.7/site-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)

cleanup-qemu_1  | binfmt: cleanup done
docker_build-nixos_1 exited with code 0
docker_cleanup-qemu_1 exited with code 0
```

**Comment by Robertof** [comment]
Hey! I'm very sorry for the late response.

This looks like an issue with `docker-compose` and specifically it looks like it's not able to connect to the Docker daemon via the standard UNIX socket. Are you using Docker on macOS and/or Windows? There's this thread on the `compose` repo which sounds like it's related to the same issue: https://github.com/docker/compose/issues/4486

**Comment by marcusramberg** [comment]
Hey. I was running it on a nixos machine. Thanks for the lead tho, will try to debug further.

**Comment by Robertof** [comment]
Interesting! It definitely looks like a weird issue, however from the first line in your log it looks like it was able to generate the NixOS image -- did it copy it to your current folder by chance? Or maybe it was that step that made it fail.

I'm happy to help either way, keep me posted! 👍

**Comment by marcusramberg** [comment]
You know, I re-ran it today and this time it worked. Not sure why, but still pleased! 

Thanks for your work on this. 

M

**Comment by Robertof** [comment]
That's great news! Thanks so much for confirming that it was most likely a transient issue and that it worked now.

I'll close the issue now but feel free to reopen (or create a new one) if this happens again.

Most importantly, thanks for using this repo!

Roberto
